package compiler;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 02 15:31:00 COT 2009
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int POW = 13;
  public static final int DIVIDE = 6;
  public static final int LN = 12;
  public static final int TAN = 11;
  public static final int NUMBER = 14;
  public static final int SEMI = 2;
  public static final int COS = 10;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int VAR = 15;
  public static final int SEN = 9;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 5;
  public static final int LPAREN = 7;
}

