#! /bin/bash

hname=$(cat /etc/hostname)
iface=eth0
echo "Escriba el nombre de la interfaz de red (eth0)"
read opt

if $(test -n "$opt"); then
	iface=$opt
fi
linea=$((ifconfig $iface | grep "inet:") || (ifconfig $iface | grep "addr:"))
myip=$(echo $linea | cut -d: -f 2 | cut -d' ' -f 1)
if $(test -z $myip); then
	echo "Error, interfaz no existe"
	exit
fi
expresion="$myip[\t\s]+$hname"
echo $expresion

if grep -P "$expresion" /etc/hosts > tmp.txt; then
	linea=$(grep -P "$expresion" /etc/hosts)
	if (echo $linea | grep "#")>tmp.txt; then
		echo "ERROR: La linea correcta ($linea) esta comentada"
		exit
	fi	
else
	echo "ERROR en archivo /etc/hosts:"
	echo "Debe poner la IP de la tarjeta de red($myip) al host($hname)"
	exit
fi

echo "Archivo /etc/hosts correcto"
echo ""

#Descarga de db.zip y configuración del pc2server
dburl="http://dl.dropbox.com/u/7089915/db.zip"
echo "Donde se encuentra el archivo db.zip (http://dl.dropbox.com/u/7089915/db.zip)"
read opt

if $(test -n "$opt"); then
	dburl=$opt
fi

if wget --tries=5 $dburl; then
	rm -r db/
	unzip db.zip
	rm db.zip
	./pc2server
else
	echo "Error al descargar el archivo $dburl"
fi

