package pee.compilador;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 20 21:42:03 COT 2009
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OBIT = 23;
  public static final int POR = 5;
  public static final int OLOG = 18;
  public static final int XORBIT = 24;
  public static final int ENTERO = 31;
  public static final int SI = 25;
  public static final int YBIT = 22;
  public static final int SEMI = 2;
  public static final int ENTONCES = 26;
  public static final int YLOG = 17;
  public static final int ENTLIT = 33;
  public static final int FIN = 29;
  public static final int MAYI = 14;
  public static final int IGUAL = 15;
  public static final int ROTI = 20;
  public static final int MIENTRAS = 27;
  public static final int ROTD = 21;
  public static final int MENI = 13;
  public static final int DIV = 6;
  public static final int ID = 34;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int DIF = 16;
  public static final int MENOS = 4;
  public static final int DPAR = 10;
  public static final int MENOR = 12;
  public static final int MOD = 7;
  public static final int IPAR = 9;
  public static final int MAYOR = 11;
  public static final int VACIO = 32;
  public static final int NOLOG = 19;
  public static final int ERRTKN = 35;
  public static final int RETORNAR = 30;
  public static final int INICIO = 28;
  public static final int MAS = 3;
}

