#! /bin/bash

EXEC=./myocr

if [ $# -gt 0 ]; then
	echo "Eliminando todos los elementos"
	$EXEC truncate

	for file in $1/*.jpg
	do
		echo "Adding $file"
		$EXEC add $file
	done
else
	echo "Inserte como parametro en que carpeta se encuentan las imágenes"
fi
